<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>VIA.WPF.Windowing</PackageId>
		<Title>VIA.WPF Windowing</Title>
		<Version>1.0.0</Version>
		<Authors>Claus Falkenstein</Authors>
		<Description>Window chrome, window command infrastructure and themed window support for VIA.WPF applications.</Description>
	</PropertyGroup>

	<PropertyGroup>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\VIA.WPF.Controls\VIA.WPF.Controls.csproj" />
		<ProjectReference Include="..\VIA.WPF.Themes\VIA.WPF.Themes.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="FluentIcons.Common" Version="2.1.325" />
		<PackageReference Include="FluentIcons.Wpf" Version="2.1.325" />
		<PackageReference Include="MahApps.Metro.IconPacks.BootstrapIcons" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.Core" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.FileIcons" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.FontAwesome" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.FontAwesome6" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.Modern" Version="6.2.1" />
		<PackageReference Include="MahApps.Metro.IconPacks.PhosphorIcons" Version="6.2.1" />
	</ItemGroup>

</Project>