// --------------------------------------------------------------------------------------------------------------------
// <copyright file="XDataGrid.cs" company="VIA.WPF">
//   Copyright (c) VIA.WPF. All rights reserved.
// </copyright>
// <remarks>
//   The grid intentionally keeps filtering and search on the WPF collection view.
//   Expensive operations such as generated metadata synchronization, filter value creation,
//   search refreshes and view-state writes are batched, lazy or debounced.
//   For very large datasets, server-side filtering/searching remains the preferred next step.
// </remarks>
// --------------------------------------------------------------------------------------------------------------------

using System.Collections;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Media3D;
using System.Windows.Threading;

namespace VIA.WPF.Controls;

#region ### Class XDataGrid ###
/// <summary>
/// Represents an extended <see cref="DataGrid"/> with column filters and free text search.
/// </summary>
[ContentProperty(nameof(Columns))]
public partial class XDataGrid : DataGrid, INotifyPropertyChanged
{
    #region ### Private Fields ###
    private readonly Dictionary<string, ObservableCollection<XDataGridFilterItem>> _columnFilterItems;
    private readonly Dictionary<string, Button> _filterButtons;
    private readonly Dictionary<XDataGridFilterItem, string> _filterItemColumnMap;
    private readonly HashSet<XDataGridFilterItem> _subscribedFilterItems;
    private readonly Predicate<object> _filterPredicate;
    private const string ActionColumnCellTemplateResourceKey = "XDataGridActionCellTemplate";
    private static readonly Dictionary<(Type Type, string PropertyName), Func<object, object?>> _propertyAccessorCache = [];
    private readonly Dictionary<string, HashSet<string>?> _activeFilterValuesCache;
    private readonly List<KeyValuePair<string, HashSet<string>>> _activeColumnFilters;
    private readonly List<string> _searchableColumnSnapshot;
    private readonly HashSet<string> _enabledFilterDefinitionKeys;
    private CancellationTokenSource? _filterItemsLoadCancellationTokenSource;
    private int _filterItemsLoadVersion;
    private bool _isCurrentFilterLoading;
    private readonly DispatcherTimer _filterRefreshTimer;
    private readonly DispatcherTimer _viewStateStoreTimer;
    private readonly HashSet<string> _autoGeneratedSearchableColumnKeys;
    private ICollectionView? _itemsView;
    private DataGridTemplateColumn? _actionColumn;
    private IEnumerable? _rawItemsSource;
    private string? _currentFilterColumnKey;
    private ObservableCollection<XDataGridFilterItem> _currentFilterItems;
    private Popup? _currentPopup;
    private Button? _currentPopupButton;
    private bool _isBulkUpdatingFilters;
    private bool _isUpdatingActionColumn;
    private bool _isRestoringViewState;
    private bool _isApplyingSort;
    private bool _isSynchronizingColumnMetadata;
    private string? _cachedViewStateKey;
    private string _activeSearchTerm = string.Empty;
    private Button? _actionColumnFilterButton;
    #endregion

    #region ### Constructors ###
    /// <summary>
    /// Initializes the <see cref="XDataGrid"/> class.
    /// </summary>
    static XDataGrid()
    {
        DefaultStyleKeyProperty.OverrideMetadata(typeof(XDataGrid), new FrameworkPropertyMetadata(typeof(XDataGrid)));
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="XDataGrid"/> class.
    /// </summary>
    public XDataGrid()
    {
        this.SelectionMode = DataGridSelectionMode.Single;

        this._columnFilterItems = [];
        this._filterButtons = [];
        this._filterItemColumnMap = [];
        this._subscribedFilterItems = [];
        this._filterPredicate = this.FilterItem;
        this._activeFilterValuesCache = [];
        this._activeColumnFilters = [];
        this._searchableColumnSnapshot = [];
        this._enabledFilterDefinitionKeys = new HashSet<string>(StringComparer.Ordinal);
        this._autoGeneratedSearchableColumnKeys = [];
        this._currentFilterItems = [];
        this._filterRefreshTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromMilliseconds(180d)
        };

        this._viewStateStoreTimer = new DispatcherTimer
        {
            Interval = TimeSpan.FromMilliseconds(250d)
        };

        this._filterRefreshTimer.Tick += this.OnFilterRefreshTimerTick;
        this._viewStateStoreTimer.Tick += this.OnViewStateStoreTimerTick;

        this.FilterDefinitions = [];
        this.SearchableColumns = [];

        this.SelectAllCurrentColumnCommand = new DelegateCommand(this.SelectAllCurrentColumn);
        this.ClearCurrentColumnCommand = new DelegateCommand(this.ClearCurrentColumn);
        this.ClearAllFiltersCommand = new DelegateCommand(this.ClearAllFilters);
        this.CloseCurrentPopupCommand = new DelegateCommand(this.CloseCurrentPopup);

        this.AddHandler(ButtonBase.ClickEvent, new RoutedEventHandler(this.OnButtonBaseClick), true);

        this.Columns.CollectionChanged += this.OnColumnsCollectionChanged;
        this.DataContextChanged += this.OnDataContextChanged;
        this.Loaded += this.OnLoaded;
        this.Unloaded += this.OnUnloaded;
        this.AutoGeneratedColumns += this.OnAutoGeneratedColumns;
    }
    #endregion

    #region ### Public Events ###
    /// <summary>
    /// Occurs when a property value changes.
    /// </summary>
    public event PropertyChangedEventHandler? PropertyChanged;
    #endregion

    #region ### Public Properties ###
    /// <summary>
    /// Gets or sets the current free text search term.
    /// </summary>
    public string SearchTerm
    {
        get => (string)GetValue(SearchTermProperty);
        set => SetValue(SearchTermProperty, value);
    }

    /// <summary>
    /// Gets or sets the collection of filter definitions.
    /// </summary>
    public ObservableCollection<XDataGridFilterDefinition> FilterDefinitions
    {
        get
        {
            ObservableCollection<XDataGridFilterDefinition>? value =
                (ObservableCollection<XDataGridFilterDefinition>?)GetValue(FilterDefinitionsProperty);

            if (value is null)
            {
                value = [];
                SetValue(FilterDefinitionsProperty, value);
            }

            return value;
        }

        set => SetValue(FilterDefinitionsProperty, value);
    }

    /// <summary>
    /// Gets or sets the collection of searchable columns.
    /// </summary>
    public ObservableCollection<string> SearchableColumns
    {
        get
        {
            ObservableCollection<string>? value =
                (ObservableCollection<string>?)GetValue(SearchableColumnsProperty);

            if (value is null)
            {
                value = [];
                SetValue(SearchableColumnsProperty, value);
            }

            return value;
        }

        set => SetValue(SearchableColumnsProperty, value);
    }

    /// <summary>
    /// Gets or sets the render mode used to highlight matching search text in text cells.
    /// </summary>
    public XHighlightRenderMode SearchMatchHighlightRenderMode
    {
        get => (XHighlightRenderMode)GetValue(SearchMatchHighlightRenderModeProperty);
        set => SetValue(SearchMatchHighlightRenderModeProperty, value);
    }

    /// <summary>
    /// Gets or sets the brush used to highlight matching search text.
    /// </summary>
    public Brush? SearchMatchHighlightBrush
    {
        get => (Brush?)GetValue(SearchMatchHighlightBrushProperty);
        set => SetValue(SearchMatchHighlightBrushProperty, value);
    }

    /// <summary>
    /// Gets or sets the foreground brush used for highlighted search text.
    /// </summary>
    public Brush? SearchMatchHighlightForeground
    {
        get => (Brush?)GetValue(SearchMatchHighlightForegroundProperty);
        set => SetValue(SearchMatchHighlightForegroundProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether filter definitions are generated automatically for all columns.
    /// </summary>
    public bool AutoGenerateFilterDefinitions
    {
        get => (bool)GetValue(AutoGenerateFilterDefinitionsProperty);
        set => SetValue(AutoGenerateFilterDefinitionsProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether searchable columns are generated automatically for all columns.
    /// </summary>
    public bool AutoGenerateSearchableColumns
    {
        get => (bool)GetValue(AutoGenerateSearchableColumnsProperty);
        set => SetValue(AutoGenerateSearchableColumnsProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether filter buttons are shown in the column headers.
    /// </summary>
    public bool ShowFilterButtons
    {
        get => (bool)GetValue(ShowFilterButtonsProperty);
        set => SetValue(ShowFilterButtonsProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the keyboard-focused cell displays an additional focus frame.
    /// </summary>
    /// <remarks>
    /// The default is <c>false</c> because full-row selection already provides the primary selection affordance.
    /// </remarks>
    public bool ShowCurrentCellFocus
    {
        get => (bool)GetValue(ShowCurrentCellFocusProperty);
        set => SetValue(ShowCurrentCellFocusProperty, value);
    }

    /// <summary>
    /// Gets or sets the active column display mode.
    /// </summary>
    public XDataGridColumnDisplayMode ColumnDisplayMode
    {
        get => (XDataGridColumnDisplayMode)GetValue(ColumnDisplayModeProperty);
        set => SetValue(ColumnDisplayModeProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the action column is shown.
    /// </summary>
    public bool ShowActionColumn
    {
        get => (bool)GetValue(ShowActionColumnProperty);
        set => SetValue(ShowActionColumnProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the view action button is shown.
    /// </summary>
    public bool ShowViewButton
    {
        get => (bool)GetValue(ShowViewButtonProperty);
        set => SetValue(ShowViewButtonProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the edit action button is shown.
    /// </summary>
    public bool ShowEditButton
    {
        get => (bool)GetValue(ShowEditButtonProperty);
        set => SetValue(ShowEditButtonProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the delete action button is shown.
    /// </summary>
    public bool ShowDeleteButton
    {
        get => (bool)GetValue(ShowDeleteButtonProperty);
        set => SetValue(ShowDeleteButtonProperty, value);
    }

    /// <summary>
    /// Gets or sets the command invoked by the row view action button.
    /// </summary>
    public ICommand? ViewItemCommand
    {
        get => (ICommand?)GetValue(ViewItemCommandProperty);
        set => SetValue(ViewItemCommandProperty, value);
    }

    /// <summary>
    /// Gets or sets the command invoked by the insert key.
    /// </summary>
    public ICommand? NewItemCommand
    {
        get => (ICommand?)GetValue(NewItemCommandProperty);
        set => SetValue(NewItemCommandProperty, value);
    }

    /// <summary>
    /// Gets or sets the command invoked by the row edit action button.
    /// </summary>
    public ICommand? EditItemCommand
    {
        get => (ICommand?)GetValue(EditItemCommandProperty);
        set => SetValue(EditItemCommandProperty, value);
    }

    /// <summary>
    /// Gets or sets the command invoked by the row delete action button.
    /// </summary>
    public ICommand? DeleteItemCommand
    {
        get => (ICommand?)GetValue(DeleteItemCommandProperty);
        set => SetValue(DeleteItemCommandProperty, value);
    }

    /// <summary>
    /// Gets or sets the optional action column header.
    /// </summary>
    public object? ActionColumnHeader
    {
        get => GetValue(ActionColumnHeaderProperty);
        set => SetValue(ActionColumnHeaderProperty, value);
    }

    /// <summary>
    /// Gets or sets the content of the full-width action column filter reset button.
    /// </summary>
    public object? ResetAllFiltersButtonContent
    {
        get => GetValue(ResetAllFiltersButtonContentProperty);
        set => SetValue(ResetAllFiltersButtonContentProperty, value);
    }

    /// <summary>
    /// Gets or sets the action column width.
    /// </summary>
    public DataGridLength ActionColumnWidth
    {
        get => (DataGridLength)GetValue(ActionColumnWidthProperty);
        set => SetValue(ActionColumnWidthProperty, value);
    }

    /// <summary>
    /// Gets or sets the minimum action column width.
    /// </summary>
    public double ActionColumnMinWidth
    {
        get => (double)GetValue(ActionColumnMinWidthProperty);
        set => SetValue(ActionColumnMinWidthProperty, value);
    }

    /// <summary>
    /// Gets or sets the maximum action column width.
    /// </summary>
    public double ActionColumnMaxWidth
    {
        get => (double)GetValue(ActionColumnMaxWidthProperty);
        set => SetValue(ActionColumnMaxWidthProperty, value);
    }

    /// <summary>
    /// Gets or sets the row action button size.
    /// </summary>
    public double ActionButtonSize
    {
        get => (double)GetValue(ActionButtonSizeProperty);
        set => SetValue(ActionButtonSizeProperty, value);
    }

    /// <summary>
    /// Gets or sets the row action button icon size.
    /// </summary>
    public double ActionButtonIconSize
    {
        get => (double)GetValue(ActionButtonIconSizeProperty);
        set => SetValue(ActionButtonIconSizeProperty, value);
    }

    /// <summary>
    /// Gets or sets the spacing between action buttons.
    /// </summary>
    public double ActionButtonSpacing
    {
        get => (double)GetValue(ActionButtonSpacingProperty);
        set => SetValue(ActionButtonSpacingProperty, value);
    }

    /// <summary>
    /// Gets or sets the tooltip of the view action button.
    /// </summary>
    public object? ViewButtonToolTip
    {
        get => GetValue(ViewButtonToolTipProperty);
        set => SetValue(ViewButtonToolTipProperty, value);
    }

    /// <summary>
    /// Gets or sets the tooltip of the edit action button.
    /// </summary>
    public object? EditButtonToolTip
    {
        get => GetValue(EditButtonToolTipProperty);
        set => SetValue(EditButtonToolTipProperty, value);
    }

    /// <summary>
    /// Gets or sets the tooltip of the delete action button.
    /// </summary>
    public object? DeleteButtonToolTip
    {
        get => GetValue(DeleteButtonToolTipProperty);
        set => SetValue(DeleteButtonToolTipProperty, value);
    }


    /// <summary>
    /// Gets or sets a value indicating whether filter, search and sort state should be persisted.
    /// </summary>
    public bool PersistViewState
    {
        get => (bool)GetValue(PersistViewStateProperty);
        set => SetValue(PersistViewStateProperty, value);
    }

    /// <summary>
    /// Gets or sets an optional key that identifies this grid for persisted view state.
    /// </summary>
    public string? ViewStateKey
    {
        get => (string?)GetValue(ViewStateKeyProperty);
        set => SetValue(ViewStateKeyProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether a row double-click invokes <see cref="EditItemCommand"/>.
    /// </summary>
    public bool EditOnRowDoubleClick
    {
        get => (bool)GetValue(EditOnRowDoubleClickProperty);
        set => SetValue(EditOnRowDoubleClickProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the enter key invokes <see cref="EditItemCommand"/> for the selected row.
    /// </summary>
    public bool EditOnEnterKey
    {
        get => (bool)GetValue(EditOnEnterKeyProperty);
        set => SetValue(EditOnEnterKeyProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the insert key invokes <see cref="NewItemCommand"/>.
    /// </summary>
    public bool NewOnInsertKey
    {
        get => (bool)GetValue(NewOnInsertKeyProperty);
        set => SetValue(NewOnInsertKeyProperty, value);
    }

    /// <summary>
    /// Gets or sets a value indicating whether the delete key invokes <see cref="DeleteItemCommand"/> for the selected row.
    /// </summary>
    public bool DeleteOnDeleteKey
    {
        get => (bool)GetValue(DeleteOnDeleteKeyProperty);
        set => SetValue(DeleteOnDeleteKeyProperty, value);
    }

    /// <summary>
    /// Gets the items of the currently opened filter popup.
    /// </summary>
    public ObservableCollection<XDataGridFilterItem> CurrentFilterItems
    {
        get => this._currentFilterItems;
        private set
        {
            if (ReferenceEquals(this._currentFilterItems, value))
            {
                return;
            }

            this._currentFilterItems = value;
            this.OnPropertyChanged();
        }
    }

    /// <summary>
    /// Gets a value indicating whether the currently opened filter popup is loading its values.
    /// </summary>
    public bool IsCurrentFilterLoading
    {
        get => this._isCurrentFilterLoading;
        private set
        {
            if (this._isCurrentFilterLoading == value)
            {
                return;
            }

            this._isCurrentFilterLoading = value;
            this.OnPropertyChanged();
        }
    }

    /// <summary>
    /// Gets the command that selects all items in the current filter popup.
    /// </summary>
    public ICommand SelectAllCurrentColumnCommand { get; }

    /// <summary>
    /// Gets the command that clears all items in the current filter popup.
    /// </summary>
    public ICommand ClearCurrentColumnCommand { get; }

    /// <summary>
    /// Clears all filters of all columns.
    /// </summary>
    public ICommand ClearAllFiltersCommand { get; }

    /// <summary>
    /// Gets the command that closes the current filter popup.
    /// </summary>
    public ICommand CloseCurrentPopupCommand { get; }
    #endregion

    #region ### Protected Methods ###
    /// <inheritdoc />
    public override void OnApplyTemplate()
    {
        base.OnApplyTemplate();
        this.EnsureActionColumn();
        this.ApplyColumnDisplayMode();
    }

    /// <summary>
    /// Called when the items source changes.
    /// </summary>
    protected override void OnItemsSourceChanged(IEnumerable oldValue, IEnumerable newValue)
    {
        base.OnItemsSourceChanged(oldValue, newValue);

        this.CancelCurrentFilterItemsLoad();
        this._rawItemsSource = ExtractRawItemsSource(newValue);

        if (!this.IsLoaded)
        {
            return;
        }

        this.AttachToItemsView();
        this.EnsureActionColumn();
        this.ApplyColumnDisplayMode();
        this.EnsureDefinitionsAndSearchableColumns();
        this.InvalidateAllColumnFilterItems();
        this.RestorePersistedViewStateOrApplyInitialSort();
        this.RefreshFilters();

        if (this.IsLoaded)
        {
            this.PrewarmPropertyAccessorCache();
        }
    }

    /// <inheritdoc />
    protected override void OnSorting(DataGridSortingEventArgs eventArgs)
    {
        if (eventArgs.Column is not null && this.TryApplyUserSort(eventArgs.Column))
        {
            eventArgs.Handled = true;
            this.ScheduleViewStateStore();
            return;
        }

        base.OnSorting(eventArgs);

        this.ScheduleViewStateStore();
    }

    /// <inheritdoc />
    protected override void OnMouseDoubleClick(MouseButtonEventArgs e)
    {
        base.OnMouseDoubleClick(e);
        this.TryExecuteEditOnRowDoubleClick(e);
    }

    /// <inheritdoc />
    protected override void OnPreviewKeyDown(KeyEventArgs e)
    {
        if (this.TryExecuteKeyboardShortcut(e))
        {
            e.Handled = true;
            return;
        }

        base.OnPreviewKeyDown(e);
    }

    #endregion

    #region ### Private Methods (Shared Helpers) ###
    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    private void AttachToItemsView()
    {
        ICollectionView? newView = this.ResolveDisplayedItemsView();

        if (!ReferenceEquals(this._itemsView, newView))
        {
            if (this._itemsView is not null)
            {
                this._itemsView.Filter = null;
            }

            this._itemsView = newView;
        }

        if (this._itemsView is not null)
        {
            Predicate<object>? newFilter = this.HasAnyActiveFilter() ? this._filterPredicate : null;

            if (!ReferenceEquals(this._itemsView.Filter, newFilter))
            {
                this._itemsView.Filter = newFilter;
            }
        }
    }

    private ICollectionView? ResolveDisplayedItemsView()
    {
        if (base.ItemsSource is not null)
        {
            return CollectionViewSource.GetDefaultView(base.ItemsSource);
        }

        return CollectionViewSource.GetDefaultView(this.Items);
    }

    private static IEnumerable? ExtractRawItemsSource(IEnumerable? itemsSource)
    {
        return itemsSource switch
        {
            null => null,
            CollectionView view => view.SourceCollection,
            CollectionViewSource source => source.Source as IEnumerable,
            _ => itemsSource
        };
    }

    private string GetColumnKey(DataGridColumn column)
    {
        if (this.IsActionColumn(column))
        {
            return string.Empty;
        }

        if (!string.IsNullOrWhiteSpace(column.SortMemberPath))
        {
            return column.SortMemberPath;
        }

        if (column is DataGridBoundColumn boundColumn &&
            boundColumn.Binding is Binding binding &&
            binding.Path is not null &&
            !string.IsNullOrWhiteSpace(binding.Path.Path))
        {
            return binding.Path.Path;
        }

        return column.Header?.ToString() ?? string.Empty;
    }

    private static bool IsSamePropertyPath(string firstPropertyName, string secondPropertyName)
    {
        return string.Equals(firstPropertyName, secondPropertyName, StringComparison.Ordinal);
    }

    internal static T? FindVisualParent<T>(DependencyObject? source)
        where T : DependencyObject
    {
        DependencyObject? current = source;

        while (current is not null)
        {
            if (current is T result)
            {
                return result;
            }

            current = GetParent(current);
        }

        return null;
    }

    private static DependencyObject? GetParent(DependencyObject source)
    {
        return source is Visual or Visual3D
            ? VisualTreeHelper.GetParent(source) ?? LogicalTreeHelper.GetParent(source)
            : LogicalTreeHelper.GetParent(source);
    }
    #endregion
}
#endregion
