// --------------------------------------------------------------------------------------------------------------------
// <copyright file="XDataGrid.Events.cs" company="VIA.WPF">
//   Copyright (c) VIA.WPF. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

using System.Collections.Specialized;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;

namespace VIA.WPF.Controls;

#region ### Class XDataGrid ###
/// <content>
/// Contains event handlers for <see cref="XDataGrid" />.
/// </content>
public partial class XDataGrid
{
    #region ### Private Event Handlers ###
    private void OnButtonBaseClick(object sender, RoutedEventArgs e)
    {
        if (e.OriginalSource is not DependencyObject source)
        {
            return;
        }

        DataGridCell? cell = FindVisualParent<DataGridCell>(source);
        if (cell?.Column is null || !this.IsActionColumn(cell.Column))
        {
            return;
        }

        this.RestoreKeyboardFocus();
    }

    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        this._cachedViewStateKey = null;

        if (!this.IsLoaded)
        {
            return;
        }

        ICollectionView? currentView = this.ResolveDisplayedItemsView();
        if (ReferenceEquals(this._itemsView, currentView))
        {
            return;
        }

        this._rawItemsSource = ExtractRawItemsSource(base.ItemsSource);
        this.AttachToItemsView();
        this.EnsureActionColumn();
        this.ApplyColumnDisplayMode();
        this.EnsureDefinitionsAndSearchableColumns();
        this.InvalidateAllColumnFilterItems();
        this.RestorePersistedViewStateOrApplyInitialSort();
        this.RefreshFilters();
        this.PrewarmPropertyAccessorCache();
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        bool viewWasAlreadyAttached = this._itemsView is not null;

        this._rawItemsSource ??= ExtractRawItemsSource(base.ItemsSource);
        this.AttachToItemsView();
        this.EnsureActionColumn();
        this.ApplyColumnDisplayMode();
        this.EnsureDefinitionsAndSearchableColumns();
        this.InvalidateAllColumnFilterItems();

        if (!viewWasAlreadyAttached)
        {
            this.RestorePersistedViewStateOrApplyInitialSort();
        }

        this.RefreshFilters();
        this.PrewarmPropertyAccessorCache();
    }

    private void OnUnloaded(object sender, RoutedEventArgs e)
    {
        this._filterRefreshTimer.Stop();
        this._viewStateStoreTimer.Stop();
        this.CancelCurrentFilterItemsLoad();
        this.StoreCurrentViewState();
        this.CloseCurrentPopup();

        if (this._itemsView is not null)
        {
            this._itemsView.Filter = null;
        }
    }

    private void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        this.EnsureActionColumn();
        this.ApplyColumnDisplayMode();
        this.EnsureDefinitionsAndSearchableColumns();
        this.InvalidateAllColumnFilterItems();
        this.RestorePersistedViewStateOrApplyInitialSort();
        this.RefreshFilters();
    }

    private void OnColumnsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        this._cachedViewStateKey = null;

        if (this._isUpdatingActionColumn)
        {
            return;
        }

        this.EnsureActionColumn();
        this.ApplyColumnDisplayMode();
        this.EnsureDefinitionsAndSearchableColumns();
        this.InvalidateAllColumnFilterItems();
    }

    private void OnFilterDefinitionsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        if (this._isSynchronizingColumnMetadata)
        {
            return;
        }

        this.InvalidateAllColumnFilterItems();
        this.RefreshFilters();
    }

    private void OnSearchableColumnsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        if (this._isSynchronizingColumnMetadata)
        {
            return;
        }

        if (e.Action == NotifyCollectionChangedAction.Reset)
        {
            this._autoGeneratedSearchableColumnKeys.Clear();
        }
        else if (e.OldItems is not null)
        {
            foreach (string columnKey in e.OldItems.OfType<string>())
            {
                this._autoGeneratedSearchableColumnKeys.Remove(columnKey);
            }
        }

        this.RefreshFilters();
    }

    private void OnFilterRefreshTimerTick(object? sender, EventArgs e)
    {
        this._filterRefreshTimer.Stop();
        this.RefreshFilters();
    }

    private void OnViewStateStoreTimerTick(object? sender, EventArgs e)
    {
        this._viewStateStoreTimer.Stop();
        this.StoreCurrentViewState();
    }
    #endregion
}
#endregion
